CREATE DATABASE NIDHI_BANK;
use NIDHI_BANK;

CREATE TABLE SUPERVISORS  (SUPERVISOR_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
                           FIRST_NAME VARCHAR(30) NOT NULL,
                           LAST_NAME VARCHAR(30),
                           BIRTH_DATE DATE NOT NULL,
                           JOINING_DATE DATE NOT NULL,
                           TERMINATION_DATE DATE,
                           PERMANENT_ADDRESS VARCHAR(200),
                           CURRENT_ADDRESS VARCHAR(200),
                           UNIQUE (FIRST_NAME, LAST_NAME, BIRTH_DATE) );

CREATE TABLE AGENTS  (AGENT_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
                      SUPERVISOR_ID INT NOT NULL,
                      FOREIGN KEY (SUPERVISOR_ID) REFERENCES SUPERVISORS(SUPERVISOR_ID),
                      FIRST_NAME VARCHAR(30) NOT NULL,
                      LAST_NAME VARCHAR(30),
                      BIRTH_DATE DATE NOT NULL,
                      JOINING_DATE DATE NOT NULL,
                      TERMINATION_DATE DATE,
                      PERMANENT_ADDRESS VARCHAR(200),
                      CURRENT_ADDRESS VARCHAR(200),
                      UNIQUE (FIRST_NAME, LAST_NAME, BIRTH_DATE));


CREATE TABLE MEMBERS (MEMBER_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
                      AGENT_ID INT NOT NULL,
                      FOREIGN KEY (AGENT_ID) REFERENCES AGENTS(AGENT_ID),
                      FIRST_NAME VARCHAR(30) NOT NULL,
                      LAST_NAME VARCHAR(30),
                      BIRTH_DATE DATE NOT NULL,
                      MEMBERSHIP_DATE DATE NOT NULL,
                      TERMINATION_DATE DATE,
                      STOCK_NUM INT NOT NULL,
                      PER_STOCK_VALUE FLOAT NOT NULL,
                      PERMANENT_ADDRESS VARCHAR(100),
                      CURRENT_ADDRESS VARCHAR(100),
                      UNIQUE (FIRST_NAME, LAST_NAME, BIRTH_DATE));


CREATE TABLE LOANS (LOAN_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
                    LOAN_NAME VARCHAR(30) NOT NULL,
                    INITIATION_DATE DATE NOT NULL,
                    ANNUAL_INTEREST_RATE FLOAT NOT NULL,
                    PRINCIPAL FLOAT NOT NULL,
                    DURATION_MONTH INT NOT NULL,
                    PRINCIPAL_BALANCE FLOAT NOT NULL,
                    PROCESSING_FEE FLOAT DEFAULT 0,
                    INTEREST_CURRENT_MONTH FLOAT NOT NULL,
                    PRINCIPAL_DEDUCTION_CURRENT_MONTH FLOAT NOT NULL,
                    PAYMENT_FREQUENCY ENUM('Daily', 'Weekly', 'Monthly', 'Yearly') NOT NULL,
                    PAYMENTS_MADE INT DEFAULT 0,
                    PAYMENTS_MISSED INT DEFAULT 0,
                    LOAN_STATUS ENUM('Active', 'Closed', 'NPA', 'Stressed') NOT NULL,
                    EQUAL_MONTHLY_INSTALLMENT FLOAT NOT NULL,
                    TOTAL_COLLECTION FLOAT DEFAULT 0,
                    PENALTY FLOAT DEFAULT 0,
                    REMARKS VARCHAR(100),
                    MEMBER_ID BIGINT NOT NULL,
                    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID),
                    SUPERVISOR_ID INT NOT NULL,
                    FOREIGN KEY (SUPERVISOR_ID) REFERENCES SUPERVISORS(SUPERVISOR_ID),
                    AGENT_ID INT NOT NULL,
                    FOREIGN KEY (AGENT_ID) REFERENCES AGENTS(AGENT_ID),
                    UNIQUE (LOAN_NAME, INITIATION_DATE, MEMBER_ID) );

CREATE TABLE MONTH_LOAN_PAYMENT ( LOAN_ID BIGINT UNSIGNED NOT NULL,
                                  COLLECTION_MONTH_YEAR DATE NOT NULL,
                                  COLLECTION_COUNT INT NOT NULL DEFAULT 0,
                                  COLLECTION_MISSED INT NOT NULL DEFAULT 0,
                                  COLLECTION_PER_DAY INT NOT NULL,
                                  COLLECTION_AMOUNT FLOAT NOT NULL DEFAULT 0,
                                  DAYS INT NOT NULL,
                                  FOREIGN KEY (LOAN_ID) REFERENCES LOANS(LOAN_ID));


CREATE TABLE RECCURING_DEPOSITS (RD_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
                    RD_NAME VARCHAR(30) NOT NULL,
                    INITIATION_DATE DATE NOT NULL,
                    LAST_INTEREST_UPDATE_DATE DATE,
                    PLANNED_CLOSING_DATE DATE,
                    ANNUAL_INTEREST_RATE FLOAT NOT NULL,
                    QUARTER_INTEREST_RATE FLOAT NOT NULL,
                    BALANCE FLOAT DEFAULT 0.0,
                    DURATION_MONTHS INT,
                    PAYMENT_FREQUENCY ENUM('Daily', 'Weekly', 'Monthly', 'Yearly') NOT NULL,
                    PAYMENTS_MADE INT DEFAULT 0,
                    PAYMENTS_MISSED INT DEFAULT 0,
                    RD_STATUS ENUM('Active', 'Closed', 'NPA', 'Stressed') NOT NULL,
                    EQUAL_DAILY_INSTALLMENT FLOAT NOT NULL,
                    PENALTY FLOAT DEFAULT 0,
                    REMARKS VARCHAR(100),
                    MEMBER_ID BIGINT NOT NULL,
                    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID),
                    SUPERVISOR_ID INT NOT NULL,
                    FOREIGN KEY (SUPERVISOR_ID) REFERENCES SUPERVISORS(SUPERVISOR_ID),
                    AGENT_ID INT NOT NULL,
                    FOREIGN KEY (AGENT_ID) REFERENCES AGENTS(AGENT_ID),
                    UNIQUE (RD_NAME, INITIATION_DATE, MEMBER_ID));


CREATE TABLE FIXED_DEPOSIT ( FD_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
                             FD_NAME VARCHAR(30) NOT NULL,
                             INITIATION_DATE DATE NOT NULL,
                             LAST_INTEREST_UPDATE_DATE DATE NOT NULL,
                             PLANNED_CLOSING_DATE DATE NOT NULL,
                             ANNUAL_INTEREST_RATE FLOAT NOT NULL,
                             TOTAL_INTEREST FLOAT NOT NULL,
                             BALANCE FLOAT NOT NULL,
                             FD_STATUS ENUM('Active', 'Closed') NOT NULL,
                             PENALTY FLOAT DEFAULT 0,
                             REMARKS VARCHAR(100),
                             MEMBER_ID BIGINT NOT NULL,
                             FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID),
                             SUPERVISOR_ID INT NOT NULL,
                             FOREIGN KEY (SUPERVISOR_ID) REFERENCES SUPERVISORS(SUPERVISOR_ID),
                             AGENT_ID INT NOT NULL,
                             FOREIGN KEY (AGENT_ID) REFERENCES AGENTS(AGENT_ID),
                             UNIQUE (FD_NAME, INITIATION_DATE, MEMBER_ID));

CREATE TABLE GOLD_LOAN  ( GOLD_LOAN_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
                          GOLD_LOAN_NAME VARCHAR(30) NOT NULL,
                          INITIATION_DATE DATE NOT NULL,
                          PLANNED_CLOSING_DATE DATE NOT NULL,
                          GOLD_MASS_GM FLOAT NOT NULL,
                          GOLD_PRICE_GM FLOAT NOT NULL,
                          ANNUAL_INTEREST_RATE FLOAT NOT NULL,
                          PRINCIPAL FLOAT NOT NULL,
                          TOTAL_INTEREST FLOAT NOT NULL,
                          BALANCE FLOAT NOT NULL,
                          DURATION INT NOT NULL,
                          PAYMENT_FREQUENCY ENUM('Daily', 'Weekly', 'Monthly', 'Yearly') NOT NULL,
                          PAYMENTS_MADE INT DEFAULT 0,
                          PAYMENTS_MISSED INT DEFAULT 0,
                          LOAN_STATUS ENUM('Active', 'Closed', 'NPA', 'Stressed') NOT NULL,
                          EQUAL_INSTALLMENT FLOAT NOT NULL,
                          PENALTY FLOAT DEFAULT 0,
                          REMARKS VARCHAR(100),
                          MEMBER_ID BIGINT NOT NULL,
                          FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID),
                          SUPERVISOR_ID INT NOT NULL,
                          FOREIGN KEY (SUPERVISOR_ID) REFERENCES SUPERVISORS(SUPERVISOR_ID),
                          AGENT_ID INT NOT NULL,
                          FOREIGN KEY (AGENT_ID) REFERENCES AGENTS(AGENT_ID));

CREATE TABLE COLLECTIONS ( COLLECTION_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
                           COLLECTION_DATE DATE NOT NULL,
                           COLLECTION_AMOUNT FLOAT NOT NULL);


CREATE TABLE COLLECTIONS_LOAN ( COLLECTION_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
                                COLLECTION_DATE DATE NOT NULL,
                                COLLECTION_AMOUNT FLOAT NOT NULL);

CREATE TABLE COLLECTIONS_RD ( COLLECTION_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
                              COLLECTION_DATE DATE NOT NULL,
                              COLLECTION_AMOUNT FLOAT NOT NULL);
